MonamourWeb/Models/Pet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace MonamourWeb.Models
{
    public class Pet : ICloneable
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "У питомца должна быть кличка")]
        [DisplayName("Кличка")]
        public string Name { get; set; }

        [DisplayName("ДР")]
        public string Bday { get; set; }

        [Required(ErrorMessage = "У питомца должна быть порода")]
        [Range(1, int.MaxValue, ErrorMessage = "Порода должна быть выбрана")]
        public int BreedId { get; set; }

        [DisplayName("Порода")]
        public Breed Breed { get; set; }
        
        [DisplayName("Инфо")]
        public string Info { get; set; }

        [NotMapped]
        public string ShortInfo
        {
            get
            {
                if (string.IsNullOrEmpty(Info))
                    return string.Empty;

                if (Info.Length > 20)
                    return Info.Substring(0, 20) + "...";
                return Info;
            }
        }

        [DisplayName("Жив")]
        public bool Alive { get; set; }

        [DisplayName("Клиенты")]
        public ICollection<Client> Clients { get; set; }
        
        [DisplayName("Теги")]
        public ICollection<PetTag> Tags { get; set; }

        public Pet()
        {
            Clients = new List<Client>();
            Tags = new List<PetTag>();
        }

        public void Update(Pet pet)
        {
            Name = pet.Name;
            Bday = pet.Bday;
            BreedId = pet.BreedId;
            Breed = pet.Breed;
            Info = pet.Info;
            Alive = pet.Alive;

            Clients = pet.Clients;
            Tags = pet.Tags;
        }

        public override string ToString()
        {
            var clients = string.Join(" ", Clients.Select(x => x.Name + " (" + x.Phone + ") [" + x.Id + "]"));
            var tags = string.Join(" ", Tags.Select(x => x.Title + " [" + x.Id + "]"));

            return $"Питомец: [Id]: {Id}; [Кличка]: {Name}; [Id породы]: {BreedId}; [Порода]: {Breed?.Title}; [Инфо]: {Info}; [ДР]: {Bday}; [Жив]: {Alive}; [Клиенты]: {clients}; [Тэги]: {tags};";
        }

        public object Clone()
        {
            return new Pet()
            {
                Id = this.Id,
                Name = this.Name,
                Bday = this.Bday,
                BreedId = this.BreedId,
                Breed = this.Breed?.Clone() as Breed,
                Info = this.Info,
                Alive = this.Alive,
                Clients = this.Clients,
                Tags = this.Tags
            };
        }
    }
}

MonamourWeb/ViewModels/PetViewModel.cs
using System.Collections.Generic;
using MonamourWeb.Models;

namespace MonamourWeb.ViewModels
{
    public class PetViewModel
    {
        public Pet Pet { get; set; }
        public List<PetTag> AllTags { get; set; }

        public PetViewModel()
        {
            Pet = new Pet();
            AllTags = new List<PetTag>();
        }
    }
}

MonamourWeb/Controllers/PetsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MonamourWeb.Models;
using MonamourWeb.Services.Filters;
using MonamourWeb.Services.Logs;
using MonamourWeb.Services.Pagination;
using MonamourWeb.ViewModels;

namespace MonamourWeb.Controllers
{
    [Authorize]
    public class PetsController : BaseController
    {
        public PetsController(MonamourDataBaseContext context, ILogService logService)
            : base(context, logService)
        {
        }

        public async Task<IActionResult> All(string sort, string search, int? tagId, int? page, int? pageSize)
        {
            var viewModel = new PetsAllViewModel();
            viewModel.PageSettings.Sort = sort;
            viewModel.PageSettings.Search = search;
            viewModel.PageSettings.PageSize = pageSize ?? 25;
            viewModel.PageSettings.PageSizes = PageSize.GetSelectListItems(pageSize);
            viewModel.Tags = Context.PetTags;
            viewModel.TagId = tagId;

            var pets = Context.Pets.Include(x => x.Clients)
                                                .Include(x => x.Tags)
                                                .Include(x => x.Breed)
                                                .AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                search = search.ToLower();
                pets = pets.Where(s => s.Name.ToLower().Contains(search)
                                                   || s.Breed.Title.Contains(search)
                                                   || s.Clients.Any(x => x.Name.ToLower().Contains(search)));
            }

            if (tagId != null)
            {
                pets = pets.Where(x => x.Tags.Any(petTag => petTag.Id == tagId));
            }

            viewModel.TotalCount = pets.Count();

            ViewData["NameSort"] = sort == "name" ? "name_desc" : "name";
            ViewData["BreedSort"] = sort == "breed" ? "breed_desc" : "breed";

            pets = sort switch
            {
                "name" => pets.OrderBy(s => s.Name),
                "name_desc" => pets.OrderByDescending(s => s.Name),
                "breed" => pets.OrderBy(s => s.Breed.Title),
                "breed_desc" => pets.OrderByDescending(s => s.Breed.Title),
                _ => pets.OrderBy(s => s.Id)
            };

            viewModel.PaginatedList = await PaginatedList<Pet>.CreateAsync(pets.AsNoTracking(), page ?? 1, pageSize ?? 25);
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new PetViewModel();
            viewModel.AllTags = Context.PetTags.ToList();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PetViewModel petViewModel, List<int> clientsOfPet, List<int> tagsOfPet)
        {
            if (ModelState.IsValid)
            {
                var clients = Context.Clients.Where(x => clientsOfPet.Contains(x.Id));
                foreach (var client in clients)
                    petViewModel.Pet.Clients.Add(client); 

                var tags = Context.PetTags.Where(x => tagsOfPet.Contains(x.Id));
                foreach (var tag in tags)
                    petViewModel.Pet.Tags.Add(tag);

                petViewModel.Pet.Alive = true;
                petViewModel.Pet.Breed = await Context.Breeds.FindAsync(petViewModel.Pet.BreedId);
                
                Context.Pets.Add(petViewModel.Pet);
                await Context.SaveChangesAsync();
                await LogService.AddCreationLogAsync<Pet>(petViewModel.Pet, UserId);
                return RedirectToAction("All");
            }
            return View(petViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> CreateQuick(string name, int id, string day)
        {
            var pet = new Pet()
            {
                Name = name,
                BreedId = id,
                Bday = day,
                Alive = true
            };

            pet.Breed = await Context.Breeds.FindAsync(id);
                
            Context.Pets.Add(pet);
            await Context.SaveChangesAsync();
            await LogService.AddCreationLogAsync<Pet>(pet, UserId);
            return Json(true);
        }

        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var pet = Context.Pets
                .Include(x => x.Breed)
                .Include(x => x.Clients)
                .Include(x => x.Tags)
                .FirstOrDefault(x => x.Id == id);

            if (pet == null)
                return NotFound();

            return View(pet);
        }

        [UserRoleFilter]
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var pet = Context.Pets
                .Include(x => x.Breed)
                .Include(x => x.Clients)
                .Include(x => x.Tags)
                .FirstOrDefault(x => x.Id == id);

            if (pet == null)
                return NotFound();

            return View(pet);
        }

        [UserRoleFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            var pet = Context.Pets
                .Include(x => x.Breed)
                .Include(x => x.Clients)
                .Include(x => x.Tags)
                .FirstOrDefault(x => x.Id == id);
            if (pet == null)
                return NotFound();
            Context.Pets.Remove(pet);
            await Context.SaveChangesAsync();
            await LogService.AddDeletedLogAsync(pet, UserId);
            return RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            var viewModel = new PetViewModel();
            viewModel.Pet = Context.Pets
                .Include(x => x.Breed)
                .Include(x => x.Tags)
                .Include(x => x.Clients)
                .FirstOrDefault(x => x.Id == id);

            if (viewModel.Pet is null)
                return NotFound();

            viewModel.AllTags = Context.PetTags.ToList();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(PetViewModel petViewModel, List<int> clientsOfPet, List<int> tagsOfPet)
        {
            if (ModelState.IsValid)
            {
                var pet = Context.Pets
                    .Include(x => x.Breed)
                    .Include(x => x.Tags)
                    .Include(x => x.Clients)
                    .FirstOrDefault(x => x.Id == petViewModel.Pet.Id);

                if (pet is null)
                    return NotFound();

                var oldPet = pet.Clone() as Pet;
                
                var clients = Context.Clients.Where(x => clientsOfPet.Contains(x.Id));
                foreach (var client in clients)
                    petViewModel.Pet.Clients.Add(client); 

                var tags = Context.PetTags.Where(x => tagsOfPet.Contains(x.Id));
                foreach (var tag in tags)
                    petViewModel.Pet.Tags.Add(tag); 

                pet.Update(petViewModel.Pet);
                pet.Breed = await Context.Breeds.FindAsync(pet.BreedId);

                await Context.SaveChangesAsync();
                await LogService.AddUpdatedLogAsync(oldPet, pet, UserId);
                return RedirectToAction("All");
            }
            return Update(petViewModel.Pet.Id);
        }
    }
}

MonamourWeb/Views/Pets/All.cshtml
@model MonamourWeb.ViewModels.PetsAllViewModel
@{
    ViewData["Title"] = "Питомцы";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h4 class="text-black-50 pl-3">Питомцы</h4>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-success" asp-area="" asp-controller="Pets" asp-action="Create">Добавить</a>
        </div>
    </div>
    <br />

    <form asp-controller="Pets" asp-action="All" method="get">
        <div class="form-group row pt-4">
            <div class="col-2 d-flex">
                <span class="fa fa-binoculars fa-lg mt-auto mb-auto mr-1"></span>
                <select asp-for="@Model.PageSettings.PageSize" name="pageSize" class="form-control ml-1">
                    @foreach (var item in Model.PageSettings.PageSizes)
                    {
                        @if (item.Value == @Model.PageSettings.PageSize.ToString())
                        {
                            <option value="@item.Value" selected>@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select>
            </div>
            <div class="col-5 d-flex">
                <span class="fa fa-filter fa-lg mt-auto mb-auto mr-1"></span>
                <input type="text" name="search" class="form-control ml-1" value="@Model.PageSettings.Search" />
            </div>
            <div class="col-3">
                <select name="tagId" class="form-control">
                    <option value="">Выберите тег</option>
                    @foreach (var item in Model.Tags)
                    {
                        @if (item.Id == Convert.ToInt32(Model.TagId))
                        {
                            <option value="@item.Id" selected>@item.Title</option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Title</option>
                        }
                    }
                </select>
            </div>
            <div class="col-2 btn-group text-right">
                <input type="submit" value="Поиск" class="btn btn-primary mr-3 btn-sm" />
                <a class="btn btn-outline-primary btn-sm" asp-controller="Pets" asp-action="All">Сбросить</a>
            </div>
        </div>
        <div class="form-group row pt-4">
            <div class="col text-right">
                <h6>Всего: @Model.TotalCount</h6>
            </div>
        </div>
    </form>

    @if (Model.PaginatedList.Any())
    {
        <table class="table table-bordered table-striped text-center" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        <a asp-action="All"
                           asp-route-sort=@ViewData["NameSort"]
                           asp-route-page="@Model.PaginatedList.PageIndex"
                           asp-route-tagId="@Model.TagId"
                           asp-route-search="@Model.PageSettings.Search"
                           asp-route-pageSize="@Model.PageSettings.PageSize">
                            @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Name)
                        </a>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Clients)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Tags)
                    </th>
                    <th>
                        <a>@Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Breed)</a>
                    </th>
                    <th>
                        <a>@Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Bday)</a>
                    </th>
                    <th>
                        <a>@Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Info)</a>
                    </th>
                    <th>
                        <a>@Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Alive)</a>
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PaginatedList)
                {
                <tr>
                    <td width="20%">
                        <a asp-controller="Pets" asp-action="Details" asp-route-Id="@item.Id">@item.Name</a>
                    </td>
                    <td width="15%">
                        @foreach (var client in item.Clients)
                        {
                            <a asp-controller="Clients" asp-action="Details" asp-route-Id="@client.Id">@client.Name</a><br />
                        }
                    </td>
                    <td width="10%">
                        @foreach (var tag in item.Tags)
                        {
                            <a class="tag-with-letter" style="background: @tag.Color" asp-controller="PetTags" asp-action="Details" asp-route-Id="@tag.Id">
                                @tag.ShortTitle
                            </a>
                        }
                    </td>
                    <td width="15%">@item.Breed.Title</td>
                    <td width="15%">@item.Bday</td>
                    <td width="20%">@item.ShortInfo</td>
                    <td width="5%">
                        @if (item.Alive)
                        {
                            <p>Да</p>
                        }
                        else
                        {
                            <p>Нет</p>
                        }
                    </td>
                    <td width="5%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Pets" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary mx-1">
                                <span class="fa fa-pen"></span>
                            </a>
                            @if (Context.User.IsInRole("Admin"))
                            {
                                <a asp-controller="Pets" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-1">
                                    <span class="fa fa-trash"></span>
                                </a>
                            }
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }

    @{
        var prevDisabled = !Model.PaginatedList.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.PaginatedList.HasNextPage ? "disabled" : "";
        var hidden = Model.PaginatedList.Count == 0 ? "d-none" : "";
    }

    <a asp-action="All"
       asp-route-sort="@Model.PageSettings.Sort"
       asp-route-page="@(Model.PaginatedList.PageIndex - 1)"
       asp-route-tagId="@Model.TagId"
       asp-route-search="@Model.PageSettings.Search"
       asp-route-pageSize="@Model.PageSettings.PageSize"
       class="btn btn-default @prevDisabled @hidden @hidden">
        <- Назад
    </a>
    <a asp-action="All"
       asp-route-sort="@Model.PageSettings.Sort"
       asp-route-page="@(Model.PaginatedList.PageIndex + 1)"
       asp-route-tagId="@Model.TagId"
       asp-route-search="@Model.PageSettings.Search"
       asp-route-pageSize="@Model.PageSettings.PageSize"
       class="btn btn-default @nextDisabled @hidden @hidden">
        Вперёд ->
    </a>
</div>

MonamourWeb/Views/Pets/Delete.cshtml
@model MonamourWeb.Models.Pet
@{
    ViewData["Title"] = "Удалить питомца";
}
<form method="post" asp-controller="Pets" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h4 class="text-black-50 pl-3">Удалить питомца</h4>
        </div>

        <table class="table table-borderless text-center" style="width: 100%">
            <tr>
                <td width="20%">
                    <label asp-for="@Model.Name"></label>
                </td>
                <td colspan="2">
                    <text class="form-control">@Model.Name</text>
                </td>
            </tr>
            <tr>
                <td width="20%">
                    <label asp-for="@Model.Breed"></label>
                </td>
                <td colspan="2">
                    <text class="form-control">@Model.Breed.Title</text>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="@Model.Clients"></label>
                </td>
                <td>
                    <select multiple id="clientsOfPets" class="form-control">
                        @foreach (var item in Model.Clients)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="@Model.Bday"></label>
                </td>
                <td colspan="2">
                    <text class="form-control">@Model.Bday</text>
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="@Model.Info"></label>
                </td>
                <td colspan="2">
                    <textarea style="height: 50px" asp-for="@Model.Info" class="form-control"></textarea>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="@Model.Tags"></label>
                </td>
                <td>
                    <select multiple id="clientsTags" class="form-control">
                        @foreach (var item in Model.Tags)
                        {
                            <option value="@item.Id">@item.Title</option>
                        }
                    </select>
                </td>
            </tr>
        </table>

        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <div class="col">
                    <input type="submit" class="btn btn-danger w-75" value="Удалить" />
                </div>
                <div class="col">
                    <a class="btn btn-info w-75" asp-controller="Pets" asp-action="All">Питомцы</a>
                </div>
            </div>
        </div>
    </div>
</form>

MonamourWeb/Views/Pets/Details.cshtml
@model MonamourWeb.Models.Pet
@{
    ViewData["Title"] = "Просмотр питомца";
}

<div class="border p-3">
    <div class="form-group row">
        <h4 class="text-black-50 pl-3">Просмотр питомца</h4>
    </div>

    <table class="table table-borderless text-center" style="width: 100%">
        <tr>
            <td width="20%">
                <label asp-for="@Model.Name"></label>
            </td>
            <td colspan="2">
                <text class="form-control">@Model.Name</text>
            </td>
        </tr>
        <tr>
            <td width="20%">
                <label asp-for="@Model.Breed"></label>
            </td>
            <td colspan="2">
                <text class="form-control">@Model.Breed.Title</text>
            </td>
        </tr>
        <tr>
            <td class="w-25">
                <label asp-for="@Model.Clients"></label>
            </td>
            <td>
                <select multiple id="clientsOfPets" class="form-control">
                    @foreach (var item in Model.Clients)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="@Model.Bday"></label>
            </td>
            <td colspan="2">
                <text class="form-control">@Model.Bday</text>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="@Model.Info"></label>
            </td>
            <td colspan="2">
                <textarea style="height: 50px" asp-for="@Model.Info" class="form-control"></textarea>
            </td>
        </tr>
        <tr>
            <td class="w-25">
                <label asp-for="@Model.Tags"></label>
            </td>
            <td>
                <select multiple id="clientsTags" class="form-control">
                    @foreach (var item in Model.Tags)
                    {
                        <option value="@item.Id">@item.Title</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="@Model.Alive"></label>
            </td>
            <td>
                @if (Model.Alive)
                {
                    <p class="form-control">Да</p>
                }
                else
                {
                    <p class="form-control">Нет</p>
                }
            </td>
        </tr>
        <tr>
    </table>

    <div class="form-group row">
        <div class="col-8 offset-2 row">
            <div class="col">
                <a class="btn btn-info w-75" asp-controller="Pets" asp-action="Update" asp-route-Id="@Model.Id">Редактировать</a>
            </div>
            <div class="col">
                <a class="btn btn-danger w-75" asp-controller="Pets" asp-action="All">Питомцы</a>
            </div>
        </div>
    </div>
</div>