MonamourWeb/Models/ClientTag.cs
using System.Collections.Generic;

namespace MonamourWeb.Models
{
    public class ClientTag : Tag
    {
        public ICollection<Client> Clients { get; set; }
        
        public ClientTag()
        {
            Clients = new List<Client>();
        }

        public override string ToString()
        {
            return $"Клиентский тег: [Id]: {Id}; [Тег]: {Title}; [Короткий тег]: {ShortTitle}; [Цвет]: {Color};";
        }


        public override object Clone()
        {
            return new ClientTag()
            {
                Id = this.Id,
                Color = this.Color,
                Title = this.Title,
                ShortTitle = this.ShortTitle
            };
        }
    }
}

MonamourWeb/Controllers/ClientTagsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MonamourWeb.Models;
using MonamourWeb.Services.Filters;
using MonamourWeb.Services.Logs;
using MonamourWeb.Services.Pagination;
using MonamourWeb.ViewModels;

namespace MonamourWeb.Controllers
{
    [Authorize]
    public class ClientTagsController : BaseTagController
    {
        public ClientTagsController(MonamourDataBaseContext context, ILogService logService) 
            : base(context, logService)
        {
        }

        public async Task<IActionResult> All()
        {
            var clientTags = Context.ClientTags;
            return View(await clientTags.AsNoTracking().ToListAsync());
        }

        [UserRoleFilter]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Colors = Colors;
            return View();
        }

        [UserRoleFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientTag clientTag)
        {
            if (ModelState.IsValid)
            {
                Context.ClientTags.Add(clientTag);
                await Context.SaveChangesAsync();
                await LogService.AddCreationLogAsync<ClientTag>(clientTag, UserId);
                return RedirectToAction("All");
            }

            ViewBag.Colors = Colors;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, int? page, int? pageSize)
        {
            if (id == null || id == 0)
                return NotFound();

            var clientTag = Context.ClientTags.Find(id);
            
            if (clientTag == null)
                return NotFound();

            var clients = Context.Clients
                                        .Include(x => x.Pets)
                                        .Where(x => x.Tags.Any(tag => tag.Id == clientTag.Id));
            var viewModel = new ClientTagDetailsViewModel();
            viewModel.PageSettings.PageSize = pageSize ?? 25;
            viewModel.PageSettings.PageSizes = PageSize.GetSelectListItems(pageSize);
            viewModel.ClientTag = clientTag;
            viewModel.PaginatedList = await PaginatedList<Client>.CreateAsync(clients.AsNoTracking(), page ?? 1, pageSize ?? 25);

            return View(viewModel);
        }

        [UserRoleFilter]
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var clientTag = Context.ClientTags.Find(id);
            
            if (clientTag == null)
                return NotFound();

            ViewBag.Colors = Colors;
            return View(clientTag);
        }

        [UserRoleFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ClientTag clientTag)
        {
            if (ModelState.IsValid)
            {
                var editableClientTag = await Context.ClientTags.FindAsync(clientTag.Id);
                if (editableClientTag == null)
                    return NotFound();

                var oldClientTag = editableClientTag.Clone() as ClientTag;

                editableClientTag.Title = clientTag.Title;
                editableClientTag.ShortTitle = clientTag.ShortTitle;
                editableClientTag.Color = clientTag.Color;

                await Context.SaveChangesAsync();
                await LogService.AddUpdatedLogAsync<ClientTag>(oldClientTag, editableClientTag, UserId);
                return RedirectToAction("All");
            }

            ViewBag.Colors = Colors;
            return Update(clientTag.Id);
        }

        [UserRoleFilter]
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var clientTag = Context.ClientTags.Find(id);

            if (clientTag == null)
                return NotFound();

            return View(clientTag);
        }


        [UserRoleFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            var clientTag = await Context.ClientTags.FindAsync(id);
            if (clientTag == null)
                return NotFound();
            Context.ClientTags.Remove(clientTag);
            await Context.SaveChangesAsync();
            await LogService.AddDeletedLogAsync<ClientTag>(clientTag, UserId);
            return RedirectToAction("All");
        }
    }
}

MonamourWeb/Views/ClientTags/All.cshtml
@model IEnumerable<MonamourWeb.Models.ClientTag>
@{
    ViewData["Title"] = "Теги клиентов";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h4 class="text-black-50 pl-3">Теги клиентов</h4>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-controller="ClientTags" asp-action="Create">Добавить</a>
        </div>
    </div>
    <br />

    @if (Model.Any())
    {
        <table class="table table-bordered table-striped text-center" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        Тег
                    </th>
                    <th>
                        Тег короткий
                    </th>
                    <th>
                        Цвет
                    </th>
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <th>
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td width="40%">
                        <a asp-controller="ClientTags" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                    </td>
                    <td width="25%" style="font-weight: bold">
                        @item.ShortTitle
                    </td>
                    <td width="25%">
                        <div margin="auto" style="margin: 0 auto; width: 30px; height: 30px; background-color: @item.Color"></div>
                    </td>
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <td width="10%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="ClientTags" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary mx-1">
                                    <span class="fa fa-pen"></span>
                                </a>
                                <a asp-controller="ClientTags" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-1">
                                    <span class="fa fa-trash"></span>
                                </a>
                            </div>
                        </td>
                    }
                </tr>
                }
            </tbody>
        </table>
    }
</div>

MonamourWeb/Views/ClientTags/Create.cshtml
@model MonamourWeb.Models.ClientTag
@{
    ViewData["Title"] = "Добавить тег клиента";
}
<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h4 class="text-black-50 pl-3">Добавить тег клиента</h4>
        </div>

        <br />

        <table class="table table-borderless text-center" style="width: 100%">
            <tr>
                <td>
                    <label asp-for="Title"></label>
                </td>
                <td>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="ShortTitle"></label>
                </td>
                <td>
                    <input asp-for="ShortTitle" class="form-control" />
                    <span asp-validation-for="ShortTitle" class="text-danger"></span>
                </td>
            </tr>
            <td>
                <label asp-for="Color"></label>
            </td>
            <td>
                <select asp-for="Color" class="form-control">
                    <option value="">Выберите цвет</option>
                    @foreach (var item in ViewBag.Colors)
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </td>
        </table>

        <br />

        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-75" value="Добавить" />
                </div>
                <div class="col">
                    <a class="btn btn-danger w-75" asp-controller="ClientTags" asp-action="All">Теги клиентов</a>
                </div>
            </div>
        </div>
    </div>
</form>

MonamourWeb/Views/ClientTags/Delete.cshtml
@model MonamourWeb.Models.ClientTag
@{
    ViewData["Title"] = "Удалить тег клиента";
}

<form method="post" asp-controller="ClientTags" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h4 class="text-black-50 pl-3">Удалить тег клиента</h4>
        </div>

        <br />

        <table class="table mx-auto table-borderless text-md-center" style="width: 50%">
            <tr>
                <td class="w-25">
                    <label asp-for="Title" class="font-weight-bold"></label>
                </td>
                <td>
                    <text>@Model.Title</text>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="ShortTitle" class="font-weight-bold"></label>
                </td>
                <td>
                    <text>@Model.ShortTitle</text>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="Color" class="font-weight-bold"></label>
                </td>
                <td>
                    <text>@Model.Color</text>
                </td>
            </tr>
        </table>

        <br />

        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <div class="col">
                    <input type="submit" class="btn btn-danger w-75" value="Удалить" />
                </div>
                <div class="col">
                    <a class="btn btn-info w-75" asp-controller="ClientTags" asp-action="All">Теги клиентов</a>
                </div>
            </div>
        </div>
    </div>
</form>

MonamourWeb/Views/ClientTags/Details.cshtml
@model MonamourWeb.ViewModels.ClientTagDetailsViewModel
@{
    ViewData["Title"] = "Клиентский тег " + @Model.ClientTag.Title;
}

<input asp-for="@Model.ClientTag.Id" hidden />
<div class="border p-3">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <h4 class="text-black-50 pl-3">Клиентский тег @Model.ClientTag.Title</h4>
    </div>

    <br />

    <table class="table mx-auto table-borderless text-md-center" style="width: 50%">
        <tr>
            <td class="w-25">
                <label asp-for="@Model.ClientTag.Title" class="font-weight-bold"></label>
            </td>
            <td>
                <text>@Model.ClientTag.Title</text>
            </td>
        </tr>
        <tr>
            <td class="w-25">
                <label asp-for="@Model.ClientTag.ShortTitle" class="font-weight-bold"></label>
            </td>
            <td>
                <text>@Model.ClientTag.ShortTitle</text>
            </td>
        </tr>
        <tr>
            <td class="w-25">
                <label asp-for="@Model.ClientTag.Color" class="font-weight-bold"></label>
            </td>
            <td>
                <div margin="auto" style="margin: 0 auto; width: 30px; height: 30px; background-color: @Model.ClientTag.Color"></div>
            </td>
        </tr>
    </table>

    <br />

    <div class="form-group row">
        <div class="col-8 offset-2 row">
            @if (Context.User.IsInRole("Admin"))
            {
                <div class="col">
                    <a asp-controller="ClientTags" asp-action="Update" asp-route-Id="@Model.ClientTag.Id" class="btn btn-info w-75">Редактировать</a>
                </div>
            }
            <div class="col">
                <a class="btn btn-info w-75" asp-controller="ClientTags" asp-action="All">Теги клиентов</a>
            </div>
        </div>
    </div>

    @if (Model.PaginatedList.Any())
    {
        <table class="table table-bordered table-striped text-center" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Pets)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Phone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Bonus)
                    </th>
                    <th>
                        <a>@Html.DisplayNameFor(model => model.PaginatedList.FirstItem.Info)</a>
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PaginatedList)
                {
                <tr>
                    <td width="25%">
                        <a asp-controller="Clients" asp-action="Details" asp-route-Id="@item.Id">@item.Name</a><br />
                    </td>
                    <td width="20%">
                        @foreach (var pet in item.Pets)
                        {
                            <a asp-controller="Pets" asp-action="Details" asp-route-Id="@pet.Id">@pet.Name</a><br />
                        }
                    </td>
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <td width="15%">@item.Phone</td>
                    }
                    else
                    {
                        <td width="15%">@item.SecretPhone</td>
                    }
                    <td width="5%">@item.Bonus</td>
                    <td width="30%">@item.ShortInfo</td>
                    <td width="5%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Clients" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary mx-1">
                                <span class="fa fa-pen"></span>
                            </a>
                            @if (Context.User.IsInRole("Admin"))
                            {
                                <a asp-controller="Clients" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-1">
                                    <span class="fa fa-trash"></span>
                                </a>
                            }
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="form-group row">
            <h6 class="text-black-50 pl-3">Нет клиентов с тегом  @Model.ClientTag.Title</h6>
        </div>
    }

    @{
        var prevDisabled = !Model.PaginatedList.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.PaginatedList.HasNextPage ? "disabled" : "";
        var hidden = Model.PaginatedList.Count == 0 ? "d-none" : "";
    }

    <a asp-action="Details"
       asp-route-id="@Model.ClientTag.Id"
       asp-route-page="@(Model.PaginatedList.PageIndex - 1)"
       asp-route-pageSize="@Model.PageSettings.PageSize"
       class="btn btn-default @prevDisabled @hidden">
        <- Назад
    </a>
    <a asp-action="Details"
       asp-route-id="@Model.ClientTag.Id"
       asp-route-page="@(Model.PaginatedList.PageIndex + 1)"
       asp-route-pageSize="@Model.PageSettings.PageSize"
       class="btn btn-default @nextDisabled @hidden">
        Вперёд ->
    </a>
</div>

MonamourWeb/Views/ClientTags/Update.cshtml
@model MonamourWeb.Models.ClientTag
@{
    ViewData["Title"] = "Редактировать тег клиента";
}

<form method="post" asp-controller="ClientTags" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h4 class="text-black-50 pl-3">Редактировать тег клиента</h4>
        </div>

        <br />

        <table class="table mx-auto table-borderless text-md-center" style="width: 100%">
            <tr>
                <td class="w-25">
                    <label asp-for="Title" class="font-weight-bold"></label>
                </td>
                <td>
                    <input asp-for="Title" value="@Model.Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="ShortTitle" class="font-weight-bold"></label>
                </td>
                <td>
                    <input asp-for="ShortTitle" value="@Model.ShortTitle" class="form-control" />
                    <span asp-validation-for="ShortTitle" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td class="w-25">
                    <label asp-for="Color" class="font-weight-bold"></label>
                </td>
                <td>
                    <select asp-for="Color" class="form-control">
                        <option value="@Model.Color" selected>@Model.Color</option>
                        @foreach (var item in ViewBag.Colors)
                        {
                            if (item == Model.Color) continue;
                            <option value="@item">@item</option>
                        }
                    </select>
                </td>
            </tr>
        </table>

        <br />

        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-75" value="Сохранить" />
                </div>
                <div class="col">
                    <a class="btn btn-danger w-75" asp-controller="ClientTags" asp-action="All">Теги клиентов</a>
                </div>
            </div>
        </div>
    </div>
</form>